In [1]:
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [2]:
#int co float chay numpy tu dong chuyen qua float het
np.array([3.14,3,4,6])

array([3.14, 3.  , 4.  , 6.  ])

In [3]:
a1=np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,2,3],[4,5,6]])
type(a2)

numpy.ndarray

In [5]:
#so hang so cot
a2.shape

(2, 3)

In [6]:
#so chieu
a2.ndim

2

In [7]:
#kieu du lieu
a2.dtype

dtype('int32')

In [8]:
#so phan tu trong mang
a2.size

6

In [9]:
#zeros: tao mang toan so 0
np.zeros([2,4])#tao mang 2 hang 4 cot

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros([2,4],dtype= int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
#tao hang cot cung kieu du lieu
np.ones([3,5],dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#tao mang tu trong khoang
np.arange(0,20,2)#tao mang tu 0 den 20 buoc nhay la 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
#tao full mang chua so bat ki
np.full((3,5),6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [14]:
#tao mang tuyen tinh giua 2 gia tri trong do 5 la khoang cach
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
#tra ve mot mang float ngau nhien trong khoang tu 0.0->1.
np.random.random([4,4])

array([[0.00214718, 0.97036491, 0.32730057, 0.78586469],
       [0.3073331 , 0.34303644, 0.01162423, 0.89716043],
       [0.36255877, 0.34302735, 0.93063795, 0.9376286 ],
       [0.62977341, 0.7893737 , 0.86753743, 0.51131231]])

In [16]:
#seed: dung de goi cac gia tri ngau nhien ma khong thay doi trne may
np.random.seed(0)
np.random.random([4,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [17]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [18]:
#random gia tri int ngau nhien
np.random.randint(1,100,[2,3])

array([[56, 29, 35],
       [ 1,  1, 37]])

In [19]:
np.random.rand(4,4)

array([[0.6176355 , 0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195, 0.6976312 ],
       [0.06022547, 0.66676672, 0.67063787, 0.21038256],
       [0.1289263 , 0.31542835, 0.36371077, 0.57019677]])

- Array index & Slicing

1. One-dimensional subarray

In [20]:
x1=np.random.randint(20,size=6)
x1

array([11,  4,  6,  4, 15,  3])

In [21]:
x1[4],x1[0]

(15, 11)

2. Multi-dimensional array

In [22]:
x2= np.random.randint((10),size=(3,4))
x2

array([[4, 4, 8, 4],
       [3, 7, 5, 5],
       [0, 1, 5, 9]])

In [23]:
#lay gia tri index
x2[1,2]

5

In [24]:
#doi gia tri index
x2[1,2]=8
x2

array([[4, 4, 8, 4],
       [3, 7, 8, 5],
       [0, 1, 5, 9]])

- Slicing: cat array

In [25]:
x1

array([11,  4,  6,  4, 15,  3])

In [26]:
x1[0:3]#lay 3 gia tri dau tien dua vao index

array([11,  4,  6])

In [27]:
x1[2:5]

array([ 6,  4, 15])

In [28]:
#cat gia tri cach nhau 2 step
x1[::2]

array([11,  6, 15])

In [29]:
x2

array([[4, 4, 8, 4],
       [3, 7, 8, 5],
       [0, 1, 5, 9]])

In [30]:
#lay 2 hang dau va 3 cot dau
x2[:2,:3]

array([[4, 4, 8],
       [3, 7, 8]])

In [31]:
#lay toan bo 2 dong dau tien
x2[:,:2]

array([[4, 4],
       [3, 7],
       [0, 1]])

3. Reshaping of Arrays & Transpose : chuyen doi du lieu sang dang khac 

In [32]:
grid=np.arange(1,10)
grid.shape

(9,)

In [33]:
#tao ma tran 3x3
grid.reshape([3,3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
x=np.array([1,2,3])
x.shape

(3,)

In [35]:
x.reshape((1,3)).shape

(1, 3)

- Transpose: chuyen hang thah cot

In [36]:
x= np.array([[1.,2.],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [37]:
x.T

array([[1., 3.],
       [2., 4.]])

4. Array Concatenation and Splitting

In [38]:
x=np.array([1,2,3])
y=np.array([3,2,1])

In [39]:
#noi 2 array vao nhau
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [40]:
grid=np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.concatenate((grid,grid))#noi array theo hang(axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [42]:
np.concatenate((grid,grid),axis=1)#noi array theo cot

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [43]:
#vstack:
x= np.array([1,2,3])
grid=np.array([[9,3,4],[4,3,2]])

In [44]:
np.vstack((x,grid))#noi theo hang voi nhau

array([[1, 2, 3],
       [9, 3, 4],
       [4, 3, 2]])

In [45]:
y=np.array([[32],[45]])
np.hstack((y,grid))#noi theo cot voi nhau

array([[32,  9,  3,  4],
       [45,  4,  3,  2]])

- Splitting arrays

In [46]:
x=np.array([1,2,3,446,56,45,3])

In [47]:
#tach chuoi
np.split(x,[3,5])

[array([1, 2, 3]), array([446,  56]), array([45,  3])]

5. Broadcastin and Vectorized operations

In [48]:
a=np.arange(3)
a

array([0, 1, 2])

In [49]:
#cong gia tri array
a+5

array([5, 6, 7])

In [50]:
b=np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
a.shape, b.shape

((3,), (3, 3))

In [52]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [53]:
a*b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [54]:
c=np.arange(3).reshape((3,1))
c

array([[0],
       [1],
       [2]])

In [55]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [56]:
a*c

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

7. Manipulating & Comparing Arrays

In [57]:
list_number=[1,2,3]
ll=np.array(list_number)
ll

array([1, 2, 3])

In [58]:
sum(ll)#sum python

6

In [59]:
np.sum(ll)#np sum

6

In [60]:
#create  a massive numpy array
massive_arr=np.random.random(1000)
massive_arr[:5]
massive_arr.shape

(1000,)

In [61]:
%timeit sum(massive_arr) 
%timeit np.sum(massive_arr)

62 µs ± 2.04 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
3.23 µs ± 98.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [62]:
np.mean(massive_arr)

0.5033281051512021

In [63]:
np.max(massive_arr)

0.9980254861986478

In [64]:
np.min(massive_arr)

5.535686500857118e-05

8. Variance: phuong & Standard Deviation: do lech chuan

In [65]:
dog_height=[600,470,170,430,300]
dog_height=np.array(dog_height)
#do lech chuan
np.std(dog_height)


147.32277488562318

In [66]:
#phuong sai
np.var(dog_height)

21704.0

In [67]:
#cach tinh do lech chuan bang can bac 2 phuong sai
np.sqrt(np.var(dog_height))

147.32277488562318

9. Sorting array

In [68]:
#np.sort: quick sort
x=np.array([2,1,3,4,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [69]:
np.argsort(x) #sap xep theo index

array([1, 0, 2, 3, 4], dtype=int64)

10. Sorting along rows or columns

In [70]:
np.random.seed(42)
matA=np.random.randint(0,10,size=(4,6))
matA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [71]:
#sap xep theo cot
np.sort(matA,axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [72]:
#sap xep theo hang
np.sort(matA,axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

11. Linear Algebra: tich vo huong 

In [73]:
A= np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[5,6],[1,2],[2,4]])
A.dot(B)#tich vo huong 
#hang dau cua A nhan cot dau cua B
#A(3x3) nhan voi B(3x2)

array([[13, 22],
       [37, 58],
       [61, 94]])

In [74]:
#B(3x2) khong nhan duoc voi A(3x3)
#muon nhan thi phai dao nguoc ma tran B thanh B(2x3)
B.T

array([[5, 1, 2],
       [6, 2, 4]])

In [75]:
B.T.dot(A)

array([[23, 31, 39],
       [42, 54, 66]])

EX: Dot Product Example

In [76]:
np.random.seed(0)
sales_amounts=np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [77]:
#tao dataframe
import pandas as pd
week_sale=pd.DataFrame(sales_amounts,index=['monday','tues','wed','thurs','fri'],
                                     columns=['bao cao su','thuoc lao','ma tuy da'])
week_sale

bao cao su  thuoc lao  ma tuy da
monday          12         15          0
tues             3          3          7
wed              9         19         18
thurs            4          6         12
fri              1          6          7

In [78]:
#gia cua array
price=np.array([20,30,90])
price.shape
dochoi_price=pd.DataFrame(price.reshape(1,3),index=['price'],columns=['bao cao su','thuoc lao','ma tuy da'])
dochoi_price

bao cao su  thuoc lao  ma tuy da
price          20         30         90

In [79]:
price=np.array([20,30,90])
price.shape

(3,)

In [80]:
week_sale.shape, dochoi_price.T.shape

((5, 3), (3, 1))

In [81]:
total=week_sale.dot(dochoi_price.T)
total

price
monday    690
tues      780
wed      2370
thurs    1340
fri       830

In [82]:
week_sale['total']=total
week_sale

bao cao su  thuoc lao  ma tuy da  total
monday          12         15          0    690
tues             3          3          7    780
wed              9         19         18   2370
thurs            4          6         12   1340
fri              1          6          7    830